language: java

services:
 - docker

before_install:
 - docker build -t https://github.com/SkyeC0re/green.git 

script:
 - docker run -d -p 127.0.0.1:80:4000 https://github.com/SkyeC0re/green.git -c "ant; ant test"
